services:
  web:
    # for testing new builds locally before pushing to Hub
    # build: ./apps/web/Dockerfile
    image: kevonstaycoding/scriptsifter-web:latest
    container_name: scriptsifter-web
    restart: always
    environment:
      - OPENAI_API_KEY
      - SUPABASE_URL
      - SUPABASE_ANON_KEY
      - SUPABASE_SERVICE_ROLE_KEY
      - SUPABASE_JWT_SECRET
      - NEXT_PUBLIC_SUPABASE_URL
      - NEXT_PUBLIC_SUPABASE_ANON_KEY
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
      - CLERK_SECRET_KEY
    ports:
      - "3000:3000" # Map your frontend's port
    depends_on:
      - transcribe
      - goldmine
      - kafka
      - postgres
      - minio
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webapp.rule=Host(`app.scriptsifter.com`)"
      - "traefik.http.routers.webapp.entrypoints=websecure"
      - "traefik.http.routers.webapp.tls.certresolver=myresolver"
    networks:
      - services
      - inet

  transcribe:
    # for testing new builds locally before pushing to Hub
    # build: ./apps/transcribe/Dockerfile
    image: kevonstaycoding/scriptsifter-transcribe:latest
    container_name: scriptsifter-transcribe
    restart: always
    environment:
      - SUPABASE_URL
      - SUPABASE_ANON_KEY
      - SUPABASE_SERVICE_ROLE_KEY
      - SUPABASE_JWT_SECRET
      - OPENAI_API_KEY
      - FLUENTFFMPEG_COV

    volumes:
      - transcribe-data:/data # Storage for downloaded files
    depends_on:
      - kafka
    networks:
      - services

  goldmine:
    # for testing new builds locally before pushing to Hub
    # build: ./apps/goldmine/Dockerfile
    image: kevonstaycoding/scriptsifter-goldmine:latest
    container_name: scriptsifter-goldmine
    restart: always
    environment:
      - SUPABASE_URL
      - SUPABASE_ANON_KEY
      - SUPABASE_SERVICE_ROLE_KEY
      - SUPABASE_JWT_SECRET
      - OPENAI_API_KEY

    depends_on:
      - kafka
    networks:
      - services

  kafka:
    image: bitnami/kafka:latest
    container_name: scriptsifter-kafka
    restart: always
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      # - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - BITNAME_DEBUG=yes
      # - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      # - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092,EXTERNAL://kafka_b:9094
      - KAFKA_BROKER_ID=1
      # - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      # - KAFKA_CFG_NODE_ID=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      # - BITNAMI_DEBUG=yes
      - KAFKA_CFG_NUM_PARTITIONS=2
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/kafka # Persist Kafka's data
    networks:
      - services

  minio:
    image: minio/minio:latest
    container_name: scriptsifter-minio
    restart: always
    ports:
      - "9000:9000" # MinIO's default port
      - "9001:9001" # MinIO's default port
    volumes:
      - minio-data:/data # Persist MinIO's data
    command: server /data --console-address ":9001"
    networks:
      - services
    labels:
      - "traefik.enable=true"
      # - "traefik.http.routers.minio.rule=Host(`minio.scriptsifter.com`)"
      # - "traefik.http.routers.minio.entrypoints=websecure"
      # - "traefik.http.routers.minio.tls.certresolver=myresolver"
      # - "traefik.http.services.minio.loadbalancer.server.port=9001"
      # Console
      - "traefik.http.routers.minio.rule=Host(`minio.scriptsifter.com`)"
      - "traefik.http.routers.minio.entrypoints=websecure"
      - "traefik.http.routers.minio.tls.certresolver=myresolver"
      - "traefik.http.routers.minio.service=minio"
      - "traefik.http.services.minio.loadbalancer.server.port=9001"
      # APi
      # - "traefik.http.routers.minio.rule=Host(`minio.scriptsifter.com`)"
      - "traefik.http.routers.minio_api.entrypoints=websecure"
      - "traefik.http.routers.minio_api.tls.certresolver=myresolver"
      - "traefik.http.routers.minio_api.service=api@minio"
      - "traefik.http.services.minio_api.loadbalancer.server.port=9000"

  postgres:
    image: postgres:latest
    container_name: scriptsifter-db
    restart: always
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persist Postgres data
    networks:
      - services

volumes:
  minio-data:
  postgres-data:
  transcribe-data:
  kafka-data:
    driver: local


networks:
  inet:
    external: true
  services:
    external: false
    driver: bridge
