services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181

  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    ports:
      - 9092

  kafka-init:
    build:
      context: ./apps/kafka/
      dockerfile: Dockerfile
    command: ["bun", "./kafkaInit.ts"]

  web:
    build:
      context: ./apps/web/
      dockerfile: Dockerfile
    ports:
      - 3000

  transcribe:
    build:
      context: ./apps/transcribe/
      dockerfile: Dockerfile
    ports:
      - 8000

  goldmine:
    build:
      context: ./apps/goldmine/
      dockerfile: Dockerfile
    ports:
      - 8001
