[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$rD4sS9vv$PJ49xLSHNY1tDFlqYpxFw."
  ]

[http.routers.api]
  rule = "Host(`monitor.scriptsifter.com`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "letsencrypt"
